config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books
  resources :suppliers
  resources :accounts
  resources :parts
  resources :assemblies

	get 'about', to: 'page#about'
  if Rails.env.development? || Rails.env.test?
    mount Railsui::Engine, at: "/railsui"
  end

  # Inherits from Railsui::PageController#index
  # To overide, add your own page#index view or change to a new root
  # Visit the start page for Rails UI any time at /railsui/start
  root action: :index, controller: "railsui/page"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: %i[ show edit update destroy ]

  # GET /authors or /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1 or /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors or /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to author_url(@author), notice: "Author was successfully created." }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1 or /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to author_url(@author), notice: "Author was successfully updated." }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1 or /authors/1.json
  def destroy
    @author.destroy!

    respond_to do |format|
      format.html { redirect_to authors_url, notice: "Author was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<article id="<%= dom_id author %>" class="py-6 prose prose-zinc dark:prose-invert">
    <p class="mb-0 font-heading font-medium">
      Name
    </p>
    <p class="my-0">
      <%= author.name %>
    </p>

   <p>
    <%= link_to "View Author", author, class: "underline" %>
  </p>

  <time class="text-zinc-600 dark:text-zinc-400 text-xs" datetime="<%= author.created_at.to_formatted_s(:long) %>">Created <%= time_ago_in_words(author.created_at) + " ago" %></time>
</article>

app/views/authors/_form.html.erb
<%= form_with(model: author) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <div class="form-group">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-input" %>
  </div>

  <div class="flex items-center justify-between flex-wrap">
    <div class="sm:flex-1 sm:mb-0 mb-6">
      <%= form.submit class: "btn btn-primary" %>
    </div>

    <% if form.object.new_record? %>
      <%= link_to "Cancel", authors_path, class: "btn btn-white" %>
    <% else %>
      <%= link_to "Cancel", author_path(@author), class: "btn btn-white" %>
    <% end %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="mb-4 pb-6 border-b dark:border-zinc-700">
    <nav aria-label="breadcrumb" class="my-6 font-heading flex text-zinc-500 dark:text-zinc-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3 list-none m-0 p-0">
        <li>
          <%= link_to "Authors", authors_path, class: "hover:underline text-primary-600 dark:text-primary-500" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-zinc-300 dark:text-zinc-500">/</span>
          </div>
          <span class="text-zinc-600 dark:text-zinc-100" aria-current="page">Edit</span>
        </li>
      </ol>
    </nav>
    <div class="flex items-center justify-between">
      <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">Edit Author</h1>
      <%= button_to "Delete", @author, method: :delete, class: "btn btn-white", form: { data: { turbo_confirm: "Are you sure?" } } %>
    </div>
  </div>

  <div>
    <%= render "form", author: @author %>
  </div>
</div>

app/views/authors/index.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="flex items-center justify-between pb-6 border-b dark:border-zinc-700 border-zinc-200">
    <h1 class="text-4xl font-medium font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">Authors</h1>
    <div class="flex items-center justify-end">
      <%= link_to "New Author", new_author_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div id="authors" class="divide-y divide-zinc-200 dark:divide-zinc-700">
    <%= render @authors %>
  </div>
</div>

app/views/authors/new.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="mb-4 pb-6 border-b dark:border-zinc-700">
    <nav aria-label="breadcrumb" class="my-6 font-heading flex text-zinc-500 dark:text-zinc-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3 list-none m-0 p-0">
        <li>
          <%= link_to "Authors", authors_path, class: "hover:underline text-primary-600 dark:text-primary-500" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-zinc-300 dark:text-zinc-500">/</span>
          </div>
          <span class="text-zinc-600 dark:text-zinc-100" aria-current="page">New</span>
        </li>
      </ol>
    </nav>
    <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">New Author</h1>
  </div>

  <div>
    <%= render "form", author: @author %>
  </div>
</div>

app/views/authors/show.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="pb-6 border-b dark:border-zinc-700 border-zinc-200">
    <nav aria-label="breadcrumb" class="my-6 font-heading flex text-zinc-500 dark:text-zinc-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3 list-none m-0 p-0">
        <li>
          <%= link_to "Authors", authors_path, class: "hover:underline text-primary-600 dark:text-primary-500" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-zinc-300 dark:text-zinc-500">/</span>
          </div>
          <span class="text-zinc-600 dark:text-zinc-100" aria-current="page">
            #<%= @author.id %>
          </span>
        </li>
      </ol>
    </nav>
    <div class="flex items-center justify-between">
      <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight flex-1">author #<%= @author.id %></h1>
      <%= link_to "Edit", edit_author_path(@author), class: "btn btn-white" %>
    </div>
  </div>
  <%= render @author %>
</div>