config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :books
  resources :suppliers
  resources :accounts
  resources :parts
  resources :assemblies

	get 'about', to: 'page#about'
  if Rails.env.development? || Rails.env.test?
    mount Railsui::Engine, at: "/railsui"
  end

  # Inherits from Railsui::PageController#index
  # To overide, add your own page#index view or change to a new root
  # Visit the start page for Rails UI any time at /railsui/start
  root action: :index, controller: "railsui/page"

  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :supplier
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[ show edit update destroy ]

  # GET /accounts or /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1 or /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts or /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to account_url(@account), notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1 or /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to account_url(@account), notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1 or /accounts/1.json
  def destroy
    @account.destroy!

    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def account_params
      params.require(:account).permit(:account_number, :supplier_id)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<article id="<%= dom_id account %>" class="py-6 prose prose-zinc dark:prose-invert">
    <p class="mb-0 font-heading font-medium">
      Account number
    </p>
    <p class="my-0">
      <%= account.account_number %>
    </p>

   <p>
    <%= link_to "View Account", account, class: "underline" %>
  </p>

  <time class="text-zinc-600 dark:text-zinc-400 text-xs" datetime="<%= account.created_at.to_formatted_s(:long) %>">Created <%= time_ago_in_words(account.created_at) + " ago" %></time>
</article>

app/views/accounts/_form.html.erb
<%= form_with(model: account) do |form| %>
  <%= render "shared/error_messages", resource: form.object %>

  <div class="form-group">
    <%= form.label :account_number, class: "form-label" %>
    <%= form.text_field :account_number, class: "form-input" %>
  </div>

  <div class="form-group">
    <%= form.label :supplier_id, class: "form-label" %>
    <%= form.collection_select( :supplier_id, Supplier.all, :id, :supplier_name, {prompt: true}, {class: "form-input"}) %>
  </div>

  <div class="flex items-center justify-between flex-wrap">
    <div class="sm:flex-1 sm:mb-0 mb-6">
      <%= form.submit class: "btn btn-primary" %>
    </div>

    <% if form.object.new_record? %>
      <%= link_to "Cancel", accounts_path, class: "btn btn-white" %>
    <% else %>
      <%= link_to "Cancel", account_path(@account), class: "btn btn-white" %>
    <% end %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="mb-4 pb-6 border-b dark:border-zinc-700">
    <nav aria-label="breadcrumb" class="my-6 font-heading flex text-zinc-500 dark:text-zinc-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3 list-none m-0 p-0">
        <li>
          <%= link_to "Accounts", accounts_path, class: "hover:underline text-primary-600 dark:text-primary-500" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-zinc-300 dark:text-zinc-500">/</span>
          </div>
          <span class="text-zinc-600 dark:text-zinc-100" aria-current="page">Edit</span>
        </li>
      </ol>
    </nav>
    <div class="flex items-center justify-between">
      <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">Edit Account</h1>
      <%= button_to "Delete", @account, method: :delete, class: "btn btn-white", form: { data: { turbo_confirm: "Are you sure?" } } %>
    </div>
  </div>

  <div>
    <%= render "form", account: @account %>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="flex items-center justify-between pb-6 border-b dark:border-zinc-700 border-zinc-200">
    <h1 class="text-4xl font-medium font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">Accounts</h1>
    <div class="flex items-center justify-end">
      <%= link_to "New Account", new_account_path, class: "btn btn-primary" %>
    </div>
  </div>

  <div id="accounts" class="divide-y divide-zinc-200 dark:divide-zinc-700">
    <%= render @accounts %>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="mb-4 pb-6 border-b dark:border-zinc-700">
    <nav aria-label="breadcrumb" class="my-6 font-heading flex text-zinc-500 dark:text-zinc-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3 list-none m-0 p-0">
        <li>
          <%= link_to "Accounts", accounts_path, class: "hover:underline text-primary-600 dark:text-primary-500" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-zinc-300 dark:text-zinc-500">/</span>
          </div>
          <span class="text-zinc-600 dark:text-zinc-100" aria-current="page">New</span>
        </li>
      </ol>
    </nav>
    <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight">New Account</h1>
  </div>

  <div>
    <%= render "form", account: @account %>
  </div>
</div>

app/views/accounts/show.html.erb
<div class="max-w-3xl mx-auto px-4 my-16">
  <div class="pb-6 border-b dark:border-zinc-700 border-zinc-200">
    <nav aria-label="breadcrumb" class="my-6 font-heading flex text-zinc-500 dark:text-zinc-200 text-sm">
      <ol class="flex flex-wrap items-center space-x-3 list-none m-0 p-0">
        <li>
          <%= link_to "Accounts", accounts_path, class: "hover:underline text-primary-600 dark:text-primary-500" %>
        </li>
        <li class="flex space-x-3">
          <div class="flex items-center">
            <span class="text-zinc-300 dark:text-zinc-500">/</span>
          </div>
          <span class="text-zinc-600 dark:text-zinc-100" aria-current="page">
            #<%= @account.id %>
          </span>
        </li>
      </ol>
    </nav>
    <div class="flex items-center justify-between">
      <h1 class="text-4xl font-semibold font-heading text-zinc-900 dark:text-zinc-100 tracking-tight flex-1">account #<%= @account.id %></h1>
      <%= link_to "Edit", edit_account_path(@account), class: "btn btn-white" %>
    </div>
  </div>
  <%= render @account %>
</div>